Repository YAPP-Github/WeSpot-Backend, pull requests merged in 2024-08, with the labels that each got.

#66 #65 - Firebase 경로를 수정한다.
  app/src/main/kotlin/com/wespot/config/FirebaseConfig.kt
  build.gradle.kts
Labels: 🌟머지 해주세요🌟, 🔨픽스🔨, 🏋️매튜🏋️

#82 #63 - 유저는 학교 데이터를 검색할 수 있다
  app/src/main/kotlin/com/wespot/config/security/CustomUrlFilter.kt
  app/src/main/kotlin/com/wespot/config/security/SecurityConfig.kt
  app/src/main/kotlin/com/wespot/school/SchoolController.kt
  core/src/main/kotlin/com/wespot/school/dto/SchoolListResponse.kt
  core/src/main/kotlin/com/wespot/school/dto/SchoolResponse.kt
  core/src/main/kotlin/com/wespot/school/port/in/SchoolUseCase.kt
  core/src/main/kotlin/com/wespot/school/port/out/SchoolPort.kt
  core/src/main/kotlin/com/wespot/school/service/SearchSchoolService.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/school/SchoolJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/school/SchoolPersistentAdapter.kt
Labels: 🌟머지 해주세요🌟, 🌱기능🌱, 🥭망고🥭

#81 #67,75 - Cursor Based Pagination을 도입하고, Sent Vote 스펙을 변경한다.
  app/src/main/kotlin/com/wespot/config/security/CustomUrlFilter.kt
  app/src/main/kotlin/com/wespot/notification/NotificationController.kt
  app/src/main/kotlin/com/wespot/report/ReportController.kt
  app/src/main/kotlin/com/wespot/vote/VoteController.kt
  app/src/test/kotlin/com/wespot/notification/infrastructure/mysql/NotificationJpaRepositoryTest.kt
  app/src/test/kotlin/com/wespot/notification/service/InquiryNotificationServiceTest.kt
  app/src/test/kotlin/com/wespot/vote/domain/CompleteBallotTest.kt
  app/src/test/kotlin/com/wespot/vote/domain/VoteTest.kt
  app/src/test/kotlin/com/wespot/vote/fixture/VoteJpaEntityFixture.kt
  app/src/test/kotlin/com/wespot/vote/infrastructure/mysql/VoteJpaRepositoryTest.kt
  app/src/test/kotlin/com/wespot/vote/service/ReceivedVoteServiceTest.kt
  app/src/test/kotlin/com/wespot/vote/service/SentVoteServiceTest.kt
  core/src/main/kotlin/com/wespot/notification/dto/NotificationResponses.kt
  core/src/main/kotlin/com/wespot/notification/port/in/InquiryNotificationUseCase.kt
  core/src/main/kotlin/com/wespot/notification/port/out/NotificationPort.kt
  core/src/main/kotlin/com/wespot/notification/service/InquiryNotificationService.kt
  core/src/main/kotlin/com/wespot/notification/service/NotificationFinder.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/VoteUserResponse.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/received/ReceivedVotesResponse.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/received/ReceivedVotesResponses.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/sent/SentVotesResponse.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/sent/SentVotesResponses.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/sent/SentVotesResultsResponse.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/sent/SingleVoteResponse.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/top1/VoteDetailResultResponseOfTop1.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/top1/VoteUserResponseOfTop1.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/top5/VoteDetailResultResponseOfTop5.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/top5/VoteUserResponseOfTop5.kt
  core/src/main/kotlin/com/wespot/vote/port/in/ReceivedVoteUseCase.kt
  core/src/main/kotlin/com/wespot/vote/port/in/SentVoteUseCase.kt
  core/src/main/kotlin/com/wespot/vote/port/out/VotePort.kt
  core/src/main/kotlin/com/wespot/vote/service/ReceivedVoteService.kt
  core/src/main/kotlin/com/wespot/vote/service/SentVoteService.kt
  core/src/main/kotlin/com/wespot/vote/service/helper/VoteServiceHelper.kt
  domain/src/main/kotlin/com/wespot/vote/CompleteBallot.kt
  domain/src/main/kotlin/com/wespot/vote/Vote.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/notification/NotificationJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/notification/NotificationPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/vote/VoteJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/vote/VotePersistenceAdapter.kt
Labels: 🌱기능🌱, 🔧리팩터링🔧, 🏋️매튜🏋️

#87 #74 - Vote, Message로 인한 제한을 구분한다.
  app/src/test/kotlin/com/wespot/report/domain/RestrictionServiceTest.kt
  app/src/test/kotlin/com/wespot/report/service/RevokeRestrictionServiceTest.kt
  app/src/test/kotlin/com/wespot/report/service/SavedReportServiceTest.kt
  app/src/test/kotlin/com/wespot/user/domain/MessageRestrictionTest.kt
  app/src/test/kotlin/com/wespot/user/domain/RestrictionTest.kt
  app/src/test/kotlin/com/wespot/user/domain/UserTest.kt
  app/src/test/kotlin/com/wespot/user/domain/VoteRestrictionTest.kt
  app/src/test/kotlin/com/wespot/user/fixture/RestrictionFixture.kt
  app/src/test/kotlin/com/wespot/user/fixture/UserFixture.kt
  app/src/test/kotlin/com/wespot/user/mapper/RestrictionMapperTest.kt
  app/src/test/kotlin/com/wespot/vote/service/SavedVoteServiceTest.kt
  app/src/test/kotlin/com/wespot/vote/service/VoteRankServiceTest.kt
  core/src/main/kotlin/com/wespot/report/service/RevokeRestrictionService.kt
  core/src/main/kotlin/com/wespot/report/service/SavedReportService.kt
  core/src/main/kotlin/com/wespot/user/port/out/RestrictionPort.kt
  core/src/main/kotlin/com/wespot/vote/dto/request/VoteRequests.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/top1/VoteResultResponseOfTop1.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/top5/VoteResultResponseOfTop5.kt
  core/src/main/kotlin/com/wespot/vote/service/SavedVoteService.kt
  domain/src/main/kotlin/com/wespot/report/RestrictionService.kt
  domain/src/main/kotlin/com/wespot/user/Restriction.kt
  domain/src/main/kotlin/com/wespot/user/RestrictionType.kt
  domain/src/main/kotlin/com/wespot/user/User.kt
  domain/src/main/kotlin/com/wespot/user/restriction/MessageRestriction.kt
  domain/src/main/kotlin/com/wespot/user/restriction/Restriction.kt
  domain/src/main/kotlin/com/wespot/user/restriction/VoteRestriction.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/adapter/RestrictionPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/entity/RestrictionJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/entity/UserJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/mapper/RestrictionMapper.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/mapper/UserMapper.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/repository/RestrictionJpaRepository.kt
Labels: 🔧리팩터링🔧, 🏋️매튜🏋️

#88 #85 - 쪽지를 일괄 발송 한다.
  app/src/main/kotlin/com/wespot/message/schedule/MessageScheduler.kt
  core/src/main/kotlin/com/wespot/message/port/in/SchedulerMessageUseCase.kt
  core/src/main/kotlin/com/wespot/message/port/out/MessagePort.kt
  core/src/main/kotlin/com/wespot/message/service/ScheduledMessageSenderService.kt
  core/src/main/kotlin/com/wespot/message/service/SendMessageService.kt
  domain/src/main/kotlin/com/wespot/message/Message.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessageJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessagePersistenceAdapter.kt
Labels: 🌱기능🌱, 🥭망고🥭

#98 #97 - 카카오 템플릿 메시지를 조회할 수 있다.
  app/src/main/kotlin/com/wespot/auth/KakaoTemplateController.kt
  app/src/main/kotlin/com/wespot/config/security/CustomUrlFilter.kt
  app/src/main/kotlin/com/wespot/config/security/SecurityConfig.kt
  app/src/test/kotlin/com/wespot/auth/fixture/KakaoTemplateFixture.kt
  app/src/test/kotlin/com/wespot/auth/service/KakaoTemplateServiceTest.kt
  core/src/main/kotlin/com/wespot/auth/dto/request/KakaoTemplateRequest.kt
  core/src/main/kotlin/com/wespot/auth/dto/response/KakaoTemplateResponse.kt
  core/src/main/kotlin/com/wespot/auth/port/in/KakaoTemplateUseCase.kt
  core/src/main/kotlin/com/wespot/auth/port/out/KakaoTemplatePort.kt
  core/src/main/kotlin/com/wespot/auth/service/kakao/KakaoTemplateService.kt
  domain/src/main/kotlin/com/wespot/auth/KakaoTemplate.kt
  domain/src/main/kotlin/com/wespot/auth/KakaoTemplateType.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/auth/KakaoTemplateJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/auth/KakaoTemplateJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/auth/KakaoTemplateMapper.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/auth/KakaoTemplatePersistentAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/entity/ProfileBackgroundJpaEntity.kt
Labels: 🌟머지 해주세요🌟, 🌱기능🌱, 🥭망고🥭

#96 #95 - 보낸 메시지 수정 및 환영 메시지 추가
  app/src/main/kotlin/com/wespot/message/GetMessageController.kt
  app/src/test/kotlin/com/wespot/auth/service/AuthServiceTest.kt
  app/src/test/kotlin/com/wespot/message/service/GetMessageServiceTest.kt
  core/src/main/kotlin/com/wespot/auth/service/AuthService.kt
  core/src/main/kotlin/com/wespot/message/dto/response/MessageResponse.kt
  core/src/main/kotlin/com/wespot/message/dto/response/SendMessageStatusResponse.kt
  core/src/main/kotlin/com/wespot/message/port/in/CreateMessageUseCase.kt
  core/src/main/kotlin/com/wespot/message/port/out/MessagePort.kt
  core/src/main/kotlin/com/wespot/message/service/CreateMessageService.kt
  core/src/main/kotlin/com/wespot/message/service/GetMessageService.kt
  core/src/main/kotlin/com/wespot/message/service/listener/MessageEventListener.kt
  domain/src/main/kotlin/com/wespot/message/Message.kt
  domain/src/main/kotlin/com/wespot/user/event/WelcomeMessageEvent.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessageJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessagePersistenceAdapter.kt
Labels: 🌟머지 해주세요🌟, 🌱기능🌱, 🔧리팩터링🔧, 🔨픽스🔨, 🥭망고🥭

#101 #100 - 현재 유저가 어떠한 제제를 당했는지 확인할 수 있는 API를 만든다.
  app/src/main/kotlin/com/wespot/user/UserController.kt
  app/src/test/kotlin/com/wespot/user/fixture/UserFixture.kt
  app/src/test/kotlin/com/wespot/user/service/CheckedUserRestrictionServiceTest.kt
  app/src/test/kotlin/com/wespot/user/service/UserSettingServiceTest.kt
  core/src/main/kotlin/com/wespot/user/dto/response/CheckedRestrictionResponse.kt
  core/src/main/kotlin/com/wespot/user/port/in/CheckedUserRestrictionUseCase.kt
  core/src/main/kotlin/com/wespot/user/service/CheckedUserRestrictionService.kt
Labels: 🌟머지 해주세요🌟, 🌱기능🌱, 🏋️매튜🏋️

#103 #102 - 에러 응답을 일관성있게 변경한다.
  app/src/main/kotlin/com/wespot/common/GlobalExceptionHandler.kt
  app/src/test/kotlin/com/wespot/common/util/ReasonPhraseUtilTest.kt
  common/src/main/kotlin/com/wespot/exception/ExceptionResponse.kt
Labels: 🔨픽스🔨, 🏋️매튜🏋️

#106 #105 - data.sql 을 운영서버에서 삭제한다.
  app/src/main/resources/data.sql
Labels: 🔨픽스🔨
