Repository YAPP-Github/WeSpot-Backend, pull requests merged in 2024-07, with the labels that each got.

#4 #3 - Hexagonal Architecture + Multi Module 설정
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/opened-pr-notification.yml
  .github/workflows/submitted-pr-review-notification.yml
  .gitignore
  app/build.gradle.kts
  app/src/main/kotlin/com/wespot/ApiApplication.kt
  app/src/main/resources/config/application-local.yml
  app/src/main/resources/config/application.yml
  build.gradle.kts
  common/build.gradle.kts
  core/build.gradle.kts
  domain/build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  infrastructure/mysql/build.gradle.kts
  settings.gradle.kts
Labels: 🌟머지 해주세요🌟, ✏️수정 요청✏️, 🌱기능🌱, 🔥리뷰 기다리는 중🔥, 🥭망고🥭

#8 #7 - 이슈 생성 시 스토리 하위에도 티켓이 자동으로 생길 수 있도록 Workflow를 수정한다.
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/create-jira-issue.yml
Labels: 🌟머지 해주세요🌟, 🧹허드렛일🧹, 🏋️매튜🏋️

#12 #11 - 애그리거트 설계에 맞춰 도메인 추가
  core/src/main/kotlin/com/wespot/message/port/in/MessageUseCase.kt
  core/src/main/kotlin/com/wespot/message/port/out/MessageStatePort.kt
  core/src/main/kotlin/com/wespot/message/service/MessageService.kt
  core/src/main/kotlin/com/wespot/notification/port/in/NotificationUseCase.kt
  core/src/main/kotlin/com/wespot/notification/port/out/NotificationStatePort.kt
  core/src/main/kotlin/com/wespot/notification/service/NotificationService.kt
  core/src/main/kotlin/com/wespot/report/port/in/ReportUseCase.kt
  core/src/main/kotlin/com/wespot/report/port/out/ReportStatePort.kt
  core/src/main/kotlin/com/wespot/report/service/ReportService.kt
  core/src/main/kotlin/com/wespot/user/port/in/UserUseCase.kt
  core/src/main/kotlin/com/wespot/user/port/out/UserStatePort.kt
  core/src/main/kotlin/com/wespot/user/service/UserService.kt
  core/src/main/kotlin/com/wespot/vote/port/in/VoteUseCase.kt
  core/src/main/kotlin/com/wespot/vote/port/out/VoteStatePort.kt
  core/src/main/kotlin/com/wespot/vote/service/VoteService.kt
  domain/src/main/kotlin/com/wespot/message/Message.kt
  domain/src/main/kotlin/com/wespot/notification/Notification.kt
  domain/src/main/kotlin/com/wespot/notification/NotificationType.kt
  domain/src/main/kotlin/com/wespot/report/Report.kt
  domain/src/main/kotlin/com/wespot/report/ReportType.kt
  domain/src/main/kotlin/com/wespot/school/EstType.kt
  domain/src/main/kotlin/com/wespot/school/School.kt
  domain/src/main/kotlin/com/wespot/school/SchoolCategory.kt
  domain/src/main/kotlin/com/wespot/school/SchoolType.kt
  domain/src/main/kotlin/com/wespot/user/FCM.kt
  domain/src/main/kotlin/com/wespot/user/Profile.kt
  domain/src/main/kotlin/com/wespot/user/Setting.kt
  domain/src/main/kotlin/com/wespot/user/Social.kt
  domain/src/main/kotlin/com/wespot/user/SocialType.kt
  domain/src/main/kotlin/com/wespot/user/User.kt
  domain/src/main/kotlin/com/wespot/vote/Ballot.kt
  domain/src/main/kotlin/com/wespot/vote/Vote.kt
  domain/src/main/kotlin/com/wespot/voteoption/VoteOption.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/common/BaseEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessageJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessageJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessagePersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/notification/NotificationJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/notification/NotificationJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/notification/NotificationPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/report/ReportJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/report/ReportJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/report/ReportPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/school/SchoolJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/school/SchoolJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/FCMJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/ProfileJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/SettingJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/SocialJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/UserJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/UserJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/UserPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/vote/BallotJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/vote/VoteJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/vote/VoteJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/vote/VotePersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/voteoption/VoteOptionJpaEntity.kt
Labels: 🌟머지 해주세요🌟, 🌱기능🌱, 🏋️매튜🏋️

#36 #35 - AuthService 테스트
  .editorconfig
  app/src/test/kotlin/com/wespot/auth/fixture/AuthFixture.kt
  app/src/test/kotlin/com/wespot/auth/service/AuthServiceTest.kt
  common/src/main/kotlin/com/wespot/DateTimeUtil.kt
  core/src/main/kotlin/com/wespot/auth/dto/response/TokenResponse.kt
  core/src/main/kotlin/com/wespot/auth/port/in/AuthUseCase.kt
  core/src/main/kotlin/com/wespot/auth/service/AuthService.kt
  core/src/main/kotlin/com/wespot/auth/service/AuthenticationService.kt
  core/src/main/kotlin/com/wespot/auth/service/PrincipalDetailService.kt
  core/src/main/kotlin/com/wespot/auth/service/jwt/JwtTokenProvider.kt
  core/src/main/kotlin/com/wespot/auth/service/jwt/JwtTokenValidator.kt
Labels: 🌟머지 해주세요🌟, 🔥리뷰 기다리는 중🔥, 🔧리팩터링🔧, 🥭망고🥭

#37 #17 - 회원가입 후 프로필 설정을 할 수 있다.
  app/src/main/kotlin/com/wespot/auth/AuthController.kt
  app/src/main/kotlin/com/wespot/config/security/CustomUrlFilter.kt
  app/src/main/kotlin/com/wespot/config/security/SecurityConfig.kt
  app/src/main/kotlin/com/wespot/user/UserController.kt
  app/src/test/kotlin/com/wespot/auth/fixture/AuthFixture.kt
  app/src/test/kotlin/com/wespot/auth/service/AuthServiceTest.kt
  app/src/test/kotlin/com/wespot/school/fixture/SchoolFixture.kt
  app/src/test/kotlin/com/wespot/user/fixture/ProfileFixture.kt
  app/src/test/kotlin/com/wespot/user/fixture/UserFixture.kt
  app/src/test/kotlin/com/wespot/user/service/UserServiceTest.kt
  core/src/main/kotlin/com/wespot/auth/dto/request/ConsentsRequest.kt
  core/src/main/kotlin/com/wespot/auth/dto/request/SignUpRequest.kt
  core/src/main/kotlin/com/wespot/auth/dto/request/UserConsentRequest.kt
  core/src/main/kotlin/com/wespot/auth/service/AuthService.kt
  core/src/main/kotlin/com/wespot/user/dto/request/UpdateProfileRequest.kt
  core/src/main/kotlin/com/wespot/user/dto/response/BackgroundListResponse.kt
  core/src/main/kotlin/com/wespot/user/dto/response/BackgroundResponse.kt
  core/src/main/kotlin/com/wespot/user/dto/response/CharacterListResponse.kt
  core/src/main/kotlin/com/wespot/user/dto/response/CharacterResponse.kt
  core/src/main/kotlin/com/wespot/user/dto/response/ProfileResponse.kt
  core/src/main/kotlin/com/wespot/user/dto/response/UserResponse.kt
  core/src/main/kotlin/com/wespot/user/port/in/UserUseCase.kt
  core/src/main/kotlin/com/wespot/user/port/out/ProfileBackgroundPort.kt
  core/src/main/kotlin/com/wespot/user/port/out/ProfileIconPort.kt
  core/src/main/kotlin/com/wespot/user/port/out/UserPort.kt
  core/src/main/kotlin/com/wespot/user/service/UserService.kt
  core/src/main/kotlin/com/wespot/vote/dto/response/UserResponse.kt
  core/src/main/kotlin/com/wespot/vote/port/out/VotePort.kt
  core/src/main/kotlin/com/wespot/vote/service/VoteService.kt
  domain/src/main/kotlin/com/wespot/user/Profile.kt
  domain/src/main/kotlin/com/wespot/user/ProfileBackground.kt
  domain/src/main/kotlin/com/wespot/user/ProfileIcon.kt
  domain/src/main/kotlin/com/wespot/user/User.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/adapter/ProfileBackgroundPersistentAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/adapter/ProfileIconPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/adapter/UserPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/entity/ProfileBackgroundJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/entity/ProfileIconJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/entity/UserJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/mapper/ProfileBackgroundMapper.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/mapper/ProfileIconMapper.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/mapper/UserMapper.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/repository/ProfileBackgroundJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/repository/ProfileIconJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/repository/UserJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/vote/VotePersistenceAdapter.kt
Labels: 🌟머지 해주세요🌟, 🌱기능🌱, 🔥리뷰 기다리는 중🔥, 🥭망고🥭

#50 #49 - 유저는 쪽지를 보내기 전, 회원을 검색할 수 있다.
  app/src/main/kotlin/com/wespot/config/security/CustomUrlFilter.kt
  app/src/main/kotlin/com/wespot/config/security/SecurityConfig.kt
  app/src/main/kotlin/com/wespot/user/SearchUserController.kt
  app/src/test/kotlin/com/wespot/school/fixture/SchoolFixture.kt
  app/src/test/kotlin/com/wespot/user/fixture/UserFixture.kt
  app/src/test/kotlin/com/wespot/user/service/SearchServiceTest.kt
  app/src/test/kotlin/com/wespot/vote/fixture/BallotFixture.kt
  app/src/test/kotlin/com/wespot/vote/fixture/BallotJpaEntityFixture.kt
  app/src/test/kotlin/com/wespot/vote/mapper/BallotMapperTest.kt
  app/src/test/kotlin/com/wespot/voteoption/domain/VoteOptionTest.kt
  app/src/test/kotlin/com/wespot/voteoption/fixture/VoteOptionFixture.kt
  app/src/test/kotlin/com/wespot/voteoption/fixture/VoteOptionJpaEntityFixture.kt
  core/src/main/kotlin/com/wespot/auth/service/RefreshTokenService.kt
  core/src/main/kotlin/com/wespot/user/dto/CursorSearchData.kt
  core/src/main/kotlin/com/wespot/user/dto/request/SearchUserRequest.kt
  core/src/main/kotlin/com/wespot/user/dto/response/UserListResponse.kt
  core/src/main/kotlin/com/wespot/user/port/in/SearchUserUseCase.kt
  core/src/main/kotlin/com/wespot/user/port/in/UserUseCase.kt
  core/src/main/kotlin/com/wespot/user/port/out/UserPort.kt
  core/src/main/kotlin/com/wespot/user/service/SearchUserService.kt
  domain/src/main/kotlin/com/wespot/auth/RefreshToken.kt
  domain/src/main/kotlin/com/wespot/user/User.kt
  domain/src/main/kotlin/com/wespot/vote/Ballot.kt
  domain/src/main/kotlin/com/wespot/voteoption/VoteOption.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/common/BaseEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/adapter/UserPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/repository/UserJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/vote/BallotMapper.kt
Labels: 🌟머지 해주세요🌟

#54 #53 - CI/CD 베포 파이프라인을 구축한다.
  .github/workflows/wespot-cd.yml
Labels: 🌟머지 해주세요🌟, 🧹허드렛일🧹

#52 #19, #21, #22 - 유저는 쪽지를 보내고, 보낸 쪽지를 수정, 확인할 수 있다
  app/src/main/kotlin/com/wespot/auth/AuthController.kt
  app/src/main/kotlin/com/wespot/config/security/CustomUrlFilter.kt
  app/src/main/kotlin/com/wespot/message/GetMessageController.kt
  app/src/main/kotlin/com/wespot/message/ModifyMessageController.kt
  app/src/main/kotlin/com/wespot/message/SendMessageController.kt
  app/src/main/kotlin/com/wespot/user/UserController.kt
  app/src/test/kotlin/com/wespot/message/fixture/MessageFixture.kt
  app/src/test/kotlin/com/wespot/message/service/GetMessageServiceTest.kt
  app/src/test/kotlin/com/wespot/message/service/MessageTimeValidatorTest.kt
  app/src/test/kotlin/com/wespot/message/service/ModifyMessageServiceTest.kt
  app/src/test/kotlin/com/wespot/message/service/SendMessageServiceTest.kt
  app/src/test/kotlin/com/wespot/user/fixture/UserFixture.kt
  common/src/main/kotlin/com/wespot/CursorUtils.kt
  core/src/main/kotlin/com/wespot/message/dto/request/SendMessageRequest.kt
  core/src/main/kotlin/com/wespot/message/dto/request/UpdateMessageRequest.kt
  core/src/main/kotlin/com/wespot/message/dto/response/MessageListResponse.kt
  core/src/main/kotlin/com/wespot/message/dto/response/MessageResponse.kt
  core/src/main/kotlin/com/wespot/message/dto/response/SendMessageResponse.kt
  core/src/main/kotlin/com/wespot/message/dto/response/SendMessageStatusResponse.kt
  core/src/main/kotlin/com/wespot/message/dto/response/UpdateMessageResponse.kt
  core/src/main/kotlin/com/wespot/message/port/in/GetMessageUseCase.kt
  core/src/main/kotlin/com/wespot/message/port/in/MessageUseCase.kt
  core/src/main/kotlin/com/wespot/message/port/in/ModifyMessageUseCase.kt
  core/src/main/kotlin/com/wespot/message/port/in/SendMessageUseCase.kt
  core/src/main/kotlin/com/wespot/message/port/out/MessagePort.kt
  core/src/main/kotlin/com/wespot/message/service/GetMessageService.kt
  core/src/main/kotlin/com/wespot/message/service/MessageFinder.kt
  core/src/main/kotlin/com/wespot/message/service/MessageSendValidator.kt
  core/src/main/kotlin/com/wespot/message/service/MessageService.kt
  core/src/main/kotlin/com/wespot/message/service/ModifyMessageService.kt
  core/src/main/kotlin/com/wespot/message/service/SendMessageService.kt
  core/src/main/kotlin/com/wespot/report/service/SavedReportService.kt
  domain/src/main/kotlin/com/wespot/message/Message.kt
  domain/src/main/kotlin/com/wespot/message/MessageTimeValidator.kt
  domain/src/main/kotlin/com/wespot/message/MessageType.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessageJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessageJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessageMapper.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/message/MessagePersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/com/wespot/user/adapter/UserPersistenceAdapter.kt
Labels: 🌱기능🌱, 🔥리뷰 기다리는 중🔥, 🔧리팩터링🔧, 🥭망고🥭
